### ISSUE TITLE
Question about the p-values from 'decoding in time'

### ISSUE THREAD

**Issue by jana254** [lposani/decodanda#7]
Hi Lorenzo, 

I was wondering in what way the significance is computed in Decodanda, and if there is a way to access the p-values for the different time points when decoding in time?

Kind regards,
Jana

**Comment by lposani** [comment]
Hi Jana, the p-values are currently computed by using the z-score of the data value against the null model distribution. This has the advantage that you only need a few dozen null repetitions to estimate the null distribution and the disadvantage that assumes that the null distribution is approximately Gaussian.

However, the decoding and CCGP functions return the full population of null values, so you can use that to compute p-values differently, if you wish to do so. For example, you could count the fraction of null values that exceed the data value to avoid the assumption that the null distribution is Gaussian (however, you might need to compute 1000+ null model shuffles to have a meaningful estimation).

**Comment by jana254** [comment]
That is very helpful, thanks!
